### ISSUE TITLE
BUFFER_SIZE

### ISSUE THREAD

**Issue by echo66** [mohayonao/audio-worker-shim#3]
Is there any reason to not allow a custom buffer size, instead of always using 1024?

**Comment by mohayonao** [comment]
In the [draft specification](http://webaudio.github.io/web-audio-api/#the-audioworker), native AudioWorker does not allow a custom buffer size, too.
So, this shim follows it. 1024 is my preference.

**Comment by echo66** [comment]
Oh, okidoki. Still, I already opened an issued in web audio api repository, regarding the buffer size in audio workers.

**Comment by echo66** [comment]
https://github.com/WebAudio/web-audio-api/issues/484

**Comment by mohayonao** [comment]
Thanks!

It is difficult to decide the best buffer size for a ScriptProcessorNode.
A small buffer size raises performance problems like a glitch.
But a large buffer size raises big latency.

This shim's goal is to provide a same interface with the native AudioWorker.
I think that the 1024 samples is a so so better size from my experience.
